travis:
  secure:
    BINSTAR_TOKEN: rbJx3aEBVr9gT7XC2QNqpzdLy/dXO3bA+mEc9vk+8JRzNznkoWNfWTsiSXqUm2uAfrheBcShfY5n5HsNiCZObUYP+iTFZ42pHM0QoNLVNQlQGrIV+uUPZU8n1lrJtLuT19Qdms5Otnh56TeOO8i3LT8x1s+n5fLwGI2N6uejCCeII6vMimRnHcdwkJgvDCVwv7fcqGDeJPezw50UHq4XzcL6LNX7CYnIvz844QCfvgoCNWM5f7fNEr9bcXz7Vhc1+YBmBjqvF+/sc11OJej0uedMmUZ+YXJbcsv2yX6CwspED8iUW36NktCMJ0T/udq7je42wQjOcor9mjF+ZzB2E8NuN4Ghmn5Y6aIeSOSETFnmAPaGesZyYSCzrzJP8fRCvUqGY7GHEZcdjbbO9AsxtNjNbK/lbrlKL28X+/As7nMzyTUIdt5XmzR6EPT9Luwg8rsHw1dy/O/IBD0xoNERYHR85VmFblKA192EI8kTd7Mk2gCQ8ZwIJBxLzH8oQYpl4Dkszn839URIHHvJuh4MJkJFUL5NGPVPJ/ohdD2y3cG+HZmClsQWtxwzDMoc7q1WrTJdNRyDg5ma+zyWPtL9U/nLph3bwbMDzFyIX6bH5th9GTY7PzrBSDVIqr+hZtqfJuE+4qkbfYkv3U7n671BfI0fjp2e5gjPorlPop30nfU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
